/**
 * @description This interface represents model structur of a Review
 * @property {number} id Unique autogenerated ID of Meme 
 * @property {string} reviewer Name of Reviewer of X-Meme 
 * @property {string} comment Actual Review 
 * @property {number} stars Number of Stars
 */
export interface IReview {
    id: number,
    reviewer: string,
    comment: string,
    stars: number
}