
/**
 * @description This interface represents model sturcture of JSON Response after upload of new meme is succesful
 * @property {number} id Autogenerated Uniqe ID of Meme after upload is successful
 */
export interface IUploadResponse {
    id: number
}